/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tmsproject;

import java.awt.Color;
import static java.awt.Color.green;
import static java.awt.Color.red;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mr Saurav
 */
public class P5_CheckStatus extends javax.swing.JFrame {

    /**
     * Creates new form P1MainPage
     */
    DefaultTableModel model;
    
    String name;
    String email;
    String subject;
    double hourNeed;
    int QuestionHave;
    String endDate;
    double dsHours;
    int dqsolve;
    String SetTaskDate;
    
    ArrayList<String> subjectList;
    ArrayList<String> al;
    
    
    public P5_CheckStatus() {
        
    }
    public P5_CheckStatus(String name, String email) {
        this.name = name;
        this.email = email;
        
        subjectList = new ArrayList<String>();
        
        initComponents();
        
        jPanel3.setVisible(false);
        jPanel2.setVisible(false);
        
        this.c = jLabel1.getBackground();
        model = (DefaultTableModel) jTable1.getModel();
        DbClass db = new DbClass();

        al = db.getDataFromUserTaskDataTable(name, email);

        int n = al.size();
        for (int i = 0; i < n; i+=7) {
            subject = al.get(i+0);
            hourNeed = Double.parseDouble(al.get(i+1));
            QuestionHave = Integer.parseInt(al.get(i+2));
            endDate = al.get(i+3);
            dsHours = Double.parseDouble(al.get(i+4));
            dqsolve = Integer.parseInt(al.get(i+5));
            SetTaskDate = al.get(i+6);
            
            subjectList.add(al.get(i+0));
            
            model.insertRow(jTable1.getRowCount(), new Object[]{
                subject,
                hourNeed,
                QuestionHave,
                endDate,
                dsHours,
                dqsolve,
                SetTaskDate
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 20));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Castellar", 3, 60)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 390, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1286, 20, 60, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Enter Subject Name : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 180, 30));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 160, 30));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "HourNeed", "QuestionHave", "EndDate", "DailyTargetHours", "DailyTargetQuestion", "SetTaskDate"
            }
        ));
        jTable1.setRowHeight(40);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 200));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 1050, 200));

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("In this subject you study");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 250, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setOpaque(true);
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 140, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("In this subject you solve ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 250, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setOpaque(true);
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 140, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setOpaque(true);
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 80, 300, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setOpaque(true);
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 230, 300, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setOpaque(true);
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 350, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setOpaque(true);
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 280, 400, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 700, 320));

        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 650, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tmsproject/Pic7SetTaskk.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setBackground(Color.red);
    }//GEN-LAST:event_jLabel1MouseEntered
    Color c;
    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setBackground(c);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(val()){
            String sub = jTextField1.getText();
            if(subjectList.contains(sub)){
                jPanel3.setVisible(true);
                
                DbClass d = new DbClass();
                
                String subject2;
                double hourNeed2;
                int QuestionHave2;
                String endDate2;
                double dsHours2;
                int dqsolve2;
                String setTaskDate2;
                
                int subjectIndex = al.indexOf(sub);
                subject2 = al.get(subjectIndex);
                hourNeed2 = Double.parseDouble(al.get(subjectIndex+1));
                QuestionHave2 = Integer.parseInt(al.get(subjectIndex+2));
                endDate2 = al.get(subjectIndex+3);
                dsHours2 = Double.parseDouble(al.get(subjectIndex+4));
                dqsolve2 = Integer.parseInt(al.get(subjectIndex+5));
                setTaskDate2 = al.get(subjectIndex+6);
                
                
                double totalStudyHours = d.getTotalStudyHours(email, sub);

                LocalDate l = LocalDate.now();
                String todayDate = l.toString();
                
                Calculations c = new Calculations();
                
                int totalDayTillNow = c.calcutateDate(setTaskDate2, todayDate);
                double iShouldCompleteTask = totalDayTillNow*dsHours2;
                
                
                int totalDayNowYouHave = c.calcutateDate(todayDate, endDate2);
                int totalDayForTaskCompletion = c.calcutateDate(setTaskDate2, endDate2);
                
//                double restStudyHours = dsHours2*totalDayForTaskCompletion-totalStudyHours;
                double restStudyHours = hourNeed2-totalStudyHours;
                double nowYouHaveToStudy = restStudyHours/totalDayNowYouHave;

                int totalQuestionSolve = d.getTotalQuestionSolve(email, sub);
//                ArrayList a2 = d.getDailyQuestionSolveTargetAndDate(email, sub);
//                int dailyQuestionSolveTarget = (int) a2.get(0);
                int iShouldCompleteTaskQuestion = totalDayTillNow*dqsolve2;
                
//                int restQuestionSolve = dqsolve2*totalDayForTaskCompletion-totalQuestionSolve;
                int restQuestionSolve = QuestionHave2-totalQuestionSolve;
                double nowYouHaveToSolve = (double)restQuestionSolve/totalDayNowYouHave;
                
                if(totalStudyHours >= iShouldCompleteTask){
                    String s = Double.toString(d.getTotalStudyHours(email, sub));
                    s = s.concat(" hrs");
                    jLabel6.setText(s);
                    jLabel6.setBackground(green);
                    
                    String s1 = "You had to study for";
                    s1 = s1.concat(Double.toString(iShouldCompleteTask));
                    s1 = s1.concat(" hrs");
                    jLabel9.setText(s1);
                    jLabel9.setBackground(Color.green);
                    
                    String s2 = "Now you have to Study ";
                    s2 = s2.concat(String.format("%.2f",nowYouHaveToStudy));
                    s2 = s2.concat(" Hours per day");
                    jLabel11.setText(s2);
                    jLabel11.setBackground(Color.green);
                } else {
                    String s = Double.toString(d.getTotalStudyHours(email, sub));
                    s = s.concat(" hrs");
                    jLabel6.setText(s);
                    jLabel6.setBackground(red);
                    
                    String s1 = "You had to study for";
                    s1 = s1.concat(Double.toString(iShouldCompleteTask));
                    s1 = s1.concat(" hrs");
                    jLabel9.setText(s1);
                    jLabel9.setBackground(red);
                    
                    String s2 = "Now you have to Study ";
                    s2 = s2.concat(String.format("%.2f",nowYouHaveToStudy));
                    s2 = s2.concat(" hours per day");
                    jLabel11.setText(s2);
                    jLabel11.setBackground(Color.red);
                }
                if(totalQuestionSolve >= iShouldCompleteTaskQuestion){
                    String s = Double.toString(d.getTotalQuestionSolve(email, sub));
                    s = s.concat(" Questions");
                    jLabel8.setText(s);
                    jLabel8.setBackground(green);
                    
                    String s1 = "You had to solve ";
                    s1 = s1.concat(Double.toString(iShouldCompleteTaskQuestion));
                    s1 = s1.concat(" questions");
                    jLabel10.setText(s1);
                    jLabel10.setBackground(Color.green);
                    
                    String s2 = "Now you have to Solve ";
//                    s2 = s2.concat(Double.toString(nowYouHaveToSolve));
                    s2 = s2.concat(String.format("%.2f",nowYouHaveToSolve));
                    s2 = s2.concat(" question per day");
                    jLabel12.setText(s2);
                    jLabel12.setBackground(Color.green);
                } else {
                    String s = Double.toString(d.getTotalQuestionSolve(email, sub));
                    s = s.concat(" questions");
                    jLabel8.setText(s);
                    jLabel8.setBackground(Color.red);
                    
                    String s1 = "You had to solve ";
                    s1 = s1.concat(Double.toString(iShouldCompleteTaskQuestion));
                    s1 = s1.concat(" questions");
                    jLabel10.setText(s1);
                    jLabel10.setBackground(Color.red);
                    
                    String s2 = "Now you have to Solve ";
                    s2 = s2.concat(String.format("%.2f",nowYouHaveToSolve));
                    s2 = s2.concat(" question per day");
                    jLabel12.setText(s2);
                    jLabel12.setBackground(Color.red);
                }
            } else {
                JOptionPane.showMessageDialog(P5_CheckStatus.this, "This is not in you list");
                jTextField1.grabFocus();
                return;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new P3_MainPage(name, email).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    void reset(){
        jTextField1.setText("");
    }
    boolean val(){
        if(jTextField1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(P5_CheckStatus.this, "Enter subject Name");
            jTextField1.grabFocus();
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P5_CheckStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P5_CheckStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P5_CheckStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P5_CheckStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P5_CheckStatus("Saurav Kumar", "saurav@gmail.com").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
